spring:
  profiles:
    active: 
    - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microcloudservice-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC   # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.gwolf.springcloud.entities       # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
    
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microcloudservice-provider-dept-8001
    prefer-ip-address: true
  
info:
  app.name: gwolf-microcloudservice-provider-dept-8001
  company.name: www.gwolf.com
  build.artifactId: $project.artifactId$
  build.version:  $project.version$
  
    
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microcloudservice-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC   # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.gwolf.springcloud.entities       # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
    
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microcloudservice-provider-dept-8001
    prefer-ip-address: true
  
info:
  app.name: gwolf-microcloudservice-provider-dept-8001
  company.name: www.gwolf.com
  build.artifactId: $project.artifactId$
  build.version:  $project.version$